  if exists ( select * from sys.tables where name = N'BSFLR')
 DROP TABLE [BSFLR];
 CREATE TABLE [BSFLR] (
[SSECL]                            Integer, 
[SACL]                             Integer, 
[SCLML]                            Integer, 
[SSTRL]                            Integer, 
[SS01]                             Integer, 
[SS02]                             Integer, 
[SS03]                             Integer, 
[SS04]                             Integer, 
[SS05]                             Integer, 
[SS06]                             Integer, 
[SS07]                             Integer, 
[SS08]                             Integer, 
[SS09]                             Integer, 
[SS10]                             Integer, 
[SS11]                             Integer, 
[SS12]                             Integer, 
[SS13]                             Integer, 
[SS14]                             Integer, 
[SS15]                             Integer, 
[SS16]                             Integer, 
[SS17]                             Integer, 
[SS18]                             Integer, 
[SS19]                             Integer, 
[SS20]                             Integer, 
[SS21]                             Integer, 
[S22]                              Integer);
