USE [Contab]
GO

/****** Object:  Table [dbo].[FCOD]    Script Date: 6/7/2024 9:38:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FCOD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[IDENT] [char](1) NOT NULL,
	[CD] [char](6) NOT NULL,
	[DENS] [varchar](32) NULL,
	[DENL] [varchar](64) NULL,
	[CASIER] [int] NULL,
	[COD_COR] [int] NULL,
	[COD_GRM] [char](3) NULL,
	[C_COR] [int] NULL,
 CONSTRAINT [PK_FCOD] PRIMARY KEY CLUSTERED 
(
	[IDENT] ASC,
	[CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

