  if exists ( select * from sys.tables where name = N'TAB_NOM')
 DROP TABLE [TAB_NOM];
 CREATE TABLE [TAB_NOM] (
[NP]                               Char(31), 
[MARCA]                            Integer, 
[CNP]                              Char(13), 
[SB]                               Char(2), 
[NRBU]                             Integer, 
[ADRESA3]                          Char(20), 
[CALIF]                            Char(10), 
[LOC]                              Char(35), 
[JUD]                              Char(10), 
[STRADA]                           Char(30), 
[COD_POS]                          Numeric(10,0), 
[NUMAR]                            Char(6), 
[BLOC]                             Char(5), 
[SCARA]                            Char(5), 
[ETAJ]                             Char(6), 
[APART]                            Char(5), 
[COD_FUNC]                         Char(6), 
[STRL]                             Integer, 
[ADRES0]                           Char(71), 
[ADRES1]                           Char(71), 
[ADRES2]                           Char(71), 
[DATAN]                            Char(10), 
[VALAB]                            Char(10), 
[ZIMOD6]                           Integer, 
[ZIMOD8]                           Integer, 
[SEMNAL]                           Char(1));
